version: "3.7"
services:
    app:
        build:
            context: "./express"
            dockerfile: ".docker/Dockerfile"
        env_file: "express/.env"
        ports:
            - "80:80"
            - "443:443"
